apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongodb.conf: |-
    dbpath=/data/mongodb
    #logpath=/data/mongodb/mongodb.log
    pidfilepath=/data/mongodb/master.pid
    directoryperdb=true
    logappend=true
    bind_ip=0.0.0.0
    port=27017
