apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2.1
          command:
          - sh
          - -c
          - "exec mongod -f /data/mongodb/conf/mongodb.conf"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-config
              mountPath: /data/mongodb/conf/
            - name: mongodb-data
              mountPath: /data/db

      volumes:
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongodb-data
          hostPath:
            path: /data/mongodb-data
